# Generated by Django 4.1.13 on 2024-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_id", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
    ]
