# Generated by Django 4.1.13 on 2024-04-30 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Snap_User",
        ),
    ]
