# Generated by Django 4.1.13 on 2024-05-01 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_user_snap_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Snap_User",
        ),
    ]
